# Example Network Policies applied to each Tenant Namespace
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: 
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enable-egress
  # namespace selected by caller
spec:
  podSelector: 
    matchLabels: {}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: enable-namespace-ingress
  # namespace selected by caller
spec:
  podSelector: 
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          akash.network/name: akash-services
  - from:
    - namespaceSelector:
        matchLabels:
          akash.network/name: {{namespace}}
