apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akash-provider
spec:
  rules:
    - host: akash-provider.localhost
      http:
        paths:
          - backend:
              serviceName: akash-provider
              servicePort: http
